<?php

return [
    'paths' => [
        base_path('modules'),
    ],
    'scan' => true,
    'map' => [
        'clients' => 'clients',
        'custom_fields' => 'core',
        'custom_values' => 'core',
        'dashboard' => 'core',
        'email_templates' => 'core',
        'families' => 'products',
        'units' => 'products',
        'tasks' => 'projects',
        'quotes' => 'quotes',
        'payments' => 'payments',
        'projects' => 'projects',
        'invoice_groups' => 'invoices',
        'payment_methods' => 'payments',
        'products' => 'products',
        'invoices' => 'invoices',
        'reports' => 'core',
        'settings' => 'core',
        'users' => 'core',
        'guest' => 'clients',
        'import' => 'core',
        'sessions' => 'core',
        'layout' => 'core',
        'mailer' => 'core',
        'upload' => 'core',
        'user_clients' => 'clients',
    ],
];
